// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(FinancialContext))]
    partial class FinancialContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.Box", b =>
                {
                    b.Property<long>("BoxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("BoxId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BoxId"));

                    b.Property<string>("BoxGoal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BoxName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("BudgetTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("BoxId");

                    b.HasIndex("CreationDate");

                    b.HasIndex("EndDate");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "EndDate");

                    b.ToTable("Boxes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Box_BudgetTarget_Positive", "\"BudgetTarget\" > 0");

                            t.HasCheckConstraint("CK_Box_CurrentBalance_NonNegative", "\"CurrentBalance\" >= 0");
                        });
                });

            modelBuilder.Entity("Core.Entities.BoxContribute", b =>
                {
                    b.Property<long>("BoxContributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BoxContributeId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<long>("BoxId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceMonth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BoxContributeId");

                    b.HasIndex("BoxId");

                    b.ToTable("BoxContributes");
                });

            modelBuilder.Entity("Core.Entities.BoxWithdraw", b =>
                {
                    b.Property<long>("BoxWithdrawId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("BoxWithdrawId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BoxWithdrawId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("BoxId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ExpenseId")
                        .HasColumnType("bigint");

                    b.HasKey("BoxWithdrawId");

                    b.HasIndex("BoxId");

                    b.HasIndex("Date");

                    b.HasIndex("ExpenseId")
                        .IsUnique()
                        .HasFilter("\"ExpenseId\" IS NOT NULL");

                    b.ToTable("BoxWithdraws", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Budget", b =>
                {
                    b.Property<long>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BudgetId"));

                    b.Property<decimal>("AvailableBalance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("BoxContribute")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<decimal>("RealExpense")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("UpdateDate")
                        .HasColumnType("date");

                    b.Property<string>("VisualType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Week")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("BudgetId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("Core.Entities.BudgetCategory", b =>
                {
                    b.Property<long>("BudgetCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BudgetCategoryId"));

                    b.Property<decimal>("AvaliableBalance")
                        .HasColumnType("numeric");

                    b.Property<long?>("BudgetId")
                        .HasColumnType("bigint");

                    b.Property<int>("BudgetStatus")
                        .HasColumnType("integer");

                    b.Property<decimal>("BudgetedAmount")
                        .HasColumnType("numeric");

                    b.Property<long?>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<decimal>("PercentUsage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SpentAmount")
                        .HasColumnType("numeric");

                    b.HasKey("BudgetCategoryId");

                    b.HasIndex("BudgetId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BudgetCategories");
                });

            modelBuilder.Entity("Core.Entities.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CategoryId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("CategoryId");

                    b.HasIndex("IsActive");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("Type");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Expense", b =>
                {
                    b.Property<long>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ExpenseId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ExpenseId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ExpensePaymentMethod")
                        .HasColumnType("integer");

                    b.Property<long?>("InstallmentExpenseId")
                        .HasColumnType("bigint");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("");

                    b.Property<long?>("RecurringExpenseId")
                        .HasColumnType("bigint");

                    b.HasKey("ExpenseId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Date");

                    b.HasIndex("ExpensePaymentMethod");

                    b.HasIndex("InstallmentExpenseId")
                        .IsUnique()
                        .HasFilter("\"InstallmentExpenseId\" IS NOT NULL");

                    b.HasIndex("RecurringExpenseId")
                        .IsUnique()
                        .HasFilter("\"RecurringExpenseId\" IS NOT NULL");

                    b.HasIndex("Date", "CategoryId");

                    b.ToTable("Expenses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Expense_Amount_NonNegative", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("Core.Entities.Income", b =>
                {
                    b.Property<long>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IncomeId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IncomeId"));

                    b.Property<bool>("AlreadyReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("IncomeMethod")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("");

                    b.Property<long?>("RecurringIncomeId")
                        .HasColumnType("bigint");

                    b.HasKey("IncomeId");

                    b.HasIndex("AlreadyReceived");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Date");

                    b.HasIndex("IncomeMethod");

                    b.HasIndex("RecurringIncomeId")
                        .IsUnique()
                        .HasFilter("\"RecurringIncomeId\" IS NOT NULL");

                    b.HasIndex("Date", "CategoryId");

                    b.ToTable("Incomes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Income_Amount_Positive", "\"Amount\" > 0");
                        });
                });

            modelBuilder.Entity("Core.Entities.InstallmentExpense", b =>
                {
                    b.Property<long>("InstallmentExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("InstallmentExpenseId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InstallmentExpenseId"));

                    b.Property<DateOnly>("FirstInstallmentDate")
                        .HasColumnType("date");

                    b.Property<decimal>("InstallmentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumberOfInstallments")
                        .HasColumnType("integer");

                    b.HasKey("InstallmentExpenseId");

                    b.HasIndex("FirstInstallmentDate");

                    b.ToTable("InstallmentExpenses", null, t =>
                        {
                            t.HasCheckConstraint("CK_InstallmentExpense_InstallmentAmount_Positive", "\"InstallmentAmount\" > 0");

                            t.HasCheckConstraint("CK_InstallmentExpense_NumberOfInstallments_Positive", "\"NumberOfInstallments\" > 0");
                        });
                });

            modelBuilder.Entity("Core.Entities.InstallmentExpenseItem", b =>
                {
                    b.Property<long>("InstallmentExpenseItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("InstallmentExpenseItemId"));

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<long>("InstallmentExpenseId")
                        .HasColumnType("bigint");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<string>("MonthReference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("InstallmentExpenseItemId");

                    b.HasIndex("InstallmentExpenseId");

                    b.ToTable("InstallmentExpenseItems");
                });

            modelBuilder.Entity("Core.Entities.RecurringExpense", b =>
                {
                    b.Property<long>("RecurringExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RecurringExpenseId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecurringExpenseId"));

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateOnly>("NextDate")
                        .HasColumnType("date");

                    b.Property<int>("RecurringFrequency")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("RecurringExpenseId");

                    b.HasIndex("IsActive");

                    b.HasIndex("NextDate");

                    b.HasIndex("RecurringFrequency");

                    b.HasIndex("IsActive", "NextDate");

                    b.ToTable("RecurringExpenses", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecurringExpense_Day_Range", "\"Day\" >= 1 AND \"Day\" <= 31");
                        });
                });

            modelBuilder.Entity("Core.Entities.RecurringIncome", b =>
                {
                    b.Property<long>("RecurringIncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RecurringIncomeId");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RecurringIncomeId"));

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateOnly>("NextDate")
                        .HasColumnType("date");

                    b.Property<int>("RecurringFrequency")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("RecurringIncomeId");

                    b.HasIndex("IsActive");

                    b.HasIndex("NextDate");

                    b.HasIndex("RecurringFrequency");

                    b.HasIndex("IsActive", "NextDate");

                    b.ToTable("RecurringIncomes", null, t =>
                        {
                            t.HasCheckConstraint("CK_RecurringIncome_Day_Range", "\"Day\" >= 1 AND \"Day\" <= 31");
                        });
                });

            modelBuilder.Entity("Core.Entities.Report", b =>
                {
                    b.Property<long>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReportId"));

                    b.Property<decimal>("EconomyRate")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("GenerationDate")
                        .HasColumnType("date");

                    b.Property<decimal>("NetBalance")
                        .HasColumnType("numeric");

                    b.Property<int>("ReportType")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalExpense")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalIncome")
                        .HasColumnType("numeric");

                    b.HasKey("ReportId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Core.Entities.ReportCategory", b =>
                {
                    b.Property<long>("ReportCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReportCategoryId"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Percent")
                        .HasColumnType("numeric");

                    b.Property<long>("ReportId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("ReportCategoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportItems");
                });

            modelBuilder.Entity("Core.Entities.WeeklyBudget", b =>
                {
                    b.Property<long>("WeeklyBudgetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WeeklyBudgetId"));

                    b.Property<long?>("BudgetId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalBudget")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalSpent")
                        .HasColumnType("numeric");

                    b.Property<int>("Week")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeekBalance")
                        .HasColumnType("numeric");

                    b.HasKey("WeeklyBudgetId");

                    b.HasIndex("BudgetId");

                    b.ToTable("WeeklyBudgets");
                });

            modelBuilder.Entity("Core.Entities.BoxContribute", b =>
                {
                    b.HasOne("Core.Entities.Box", "Box")
                        .WithMany("Contribute")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");
                });

            modelBuilder.Entity("Core.Entities.BoxWithdraw", b =>
                {
                    b.HasOne("Core.Entities.Box", "Box")
                        .WithMany("Withdraw")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Expense", "Expense")
                        .WithOne()
                        .HasForeignKey("Core.Entities.BoxWithdraw", "ExpenseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Box");

                    b.Navigation("Expense");
                });

            modelBuilder.Entity("Core.Entities.BudgetCategory", b =>
                {
                    b.HasOne("Core.Entities.Budget", "Budget")
                        .WithMany("Categories")
                        .HasForeignKey("BudgetId");

                    b.HasOne("Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Budget");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Entities.Expense", b =>
                {
                    b.HasOne("Core.Entities.Category", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.InstallmentExpense", "InstallmentExpense")
                        .WithOne("Expense")
                        .HasForeignKey("Core.Entities.Expense", "InstallmentExpenseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Core.Entities.RecurringExpense", "RecurringExpense")
                        .WithOne("Expense")
                        .HasForeignKey("Core.Entities.Expense", "RecurringExpenseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("InstallmentExpense");

                    b.Navigation("RecurringExpense");
                });

            modelBuilder.Entity("Core.Entities.Income", b =>
                {
                    b.HasOne("Core.Entities.Category", "Category")
                        .WithMany("Incomes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.RecurringIncome", "RecurringIncome")
                        .WithOne("Income")
                        .HasForeignKey("Core.Entities.Income", "RecurringIncomeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("RecurringIncome");
                });

            modelBuilder.Entity("Core.Entities.InstallmentExpenseItem", b =>
                {
                    b.HasOne("Core.Entities.InstallmentExpense", "InstallmentExpense")
                        .WithMany("Items")
                        .HasForeignKey("InstallmentExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstallmentExpense");
                });

            modelBuilder.Entity("Core.Entities.ReportCategory", b =>
                {
                    b.HasOne("Core.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Core.Entities.Report", "Report")
                        .WithMany("Categories")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Core.Entities.WeeklyBudget", b =>
                {
                    b.HasOne("Core.Entities.Budget", "Budget")
                        .WithMany("WeeklyBudgets")
                        .HasForeignKey("BudgetId");

                    b.Navigation("Budget");
                });

            modelBuilder.Entity("Core.Entities.Box", b =>
                {
                    b.Navigation("Contribute");

                    b.Navigation("Withdraw");
                });

            modelBuilder.Entity("Core.Entities.Budget", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("WeeklyBudgets");
                });

            modelBuilder.Entity("Core.Entities.Category", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Incomes");
                });

            modelBuilder.Entity("Core.Entities.InstallmentExpense", b =>
                {
                    b.Navigation("Expense");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Core.Entities.RecurringExpense", b =>
                {
                    b.Navigation("Expense");
                });

            modelBuilder.Entity("Core.Entities.RecurringIncome", b =>
                {
                    b.Navigation("Income");
                });

            modelBuilder.Entity("Core.Entities.Report", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
